### ISSUE TITLE
Gene Ontology tab additions

### ISSUE THREAD

**Issue by jimmybgammyknee** [awaisc/motifOverlapR#4]
Add a few extra options to the gene ontology tab, such as:

- [x] GO IDs for each of the enriched terms

- [x] Links to QuickGO for summary of the term

- [x] Option to either have DE gene filtered, or unfiltered

**Comment by awaisc** [comment]
![geneontologytab](https://user-images.githubusercontent.com/25577229/34908520-dede0606-f8e0-11e7-89a3-533ccb0e8ece.png)
I have linked it so that so that each go term can be clicked and it'll take you to the quickgo gene ontology page! additionally, the sliders are on the side for both the adjusted and Raw P-value and an autocomplete for gene ontology type. 

The table appears to render independently of the box size (I did make them equal, but based on the number of terms showing the table will be longer/shorter).
